# Generated by Django 4.2 on 2023-04-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser')),
                ('address', models.CharField(max_length=100)),
                ('is_intern', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=12)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position')),
            ],
            bases=('users.customuser',),
        ),
    ]
